### ISSUE TITLE
Let's discuss metadata instead of regex

### ISSUE THREAD

**Issue by Mirodin** [redstreet/beancount_asset_allocation#1]
Thanks again for writing this, it produces correct results after I modify my beancount file (i.e. renaming accounts).

However I still think metadata attached to individual accounts would be a better option rather than a regular expression:

- I have a "grown" account hierarchy and renaming a lot of them breaks my inner Zen ;)
- Attaching an asset allocation percentage to my main currency (EUR) seems a bit strange - see notes below
- Balancing based on commodities seems intuitive at first but I started to stumble as soon as I wanted to include my real estate (which I tracked in EUR)
- Assigning individual account to a asset classes would ease changes as I do not have/need a commodity for every asset

Real world examples form my beancount file:

- As I mentioned above I track my real estate in EUR since that is what their value is measured at. I did pay x for that house/appartment and do not track if its value changes over the years. The only moment I care about the "real" value is when it is sold.
- I lend out money via Mintos. Those loans are in EUR, however I would like to see those on their own, as they are a somewhat risky asset class and not the same as money in my nest egg.

I hope my points are somewhat comprehensible, feel free to ask for clarification if you have any questions.

**Comment by redstreet** [comment]
Thanks for the feedback! Here's my take: a good design would solve for the general case that makes most sense. In general, commodities can inherently be associated with asset classes. However, accounts aren't inherently associated with asset classes, unless a user decides to organize their accounts that way. Even for such users, I'd imagine that specifying asset classes for commodities would solve their case. But I may be mistaken, so let's explore your use cases more:

>     * I have a "grown" account hierarchy and renaming a lot of them breaks my inner Zen ;)

- you should not have to rename your account hierarchy. Instead, you can specify as many patterns after --accounts as you want. Example:
````
--accounts "Assets:Investments:Brokerage.*" "Assets:Banks:Bank1" "Assets:Banks:Bank3"
````
Does that help?


>     * Attaching an asset allocation percentage to my main currency (EUR) seems a bit strange - see notes below

The idea here is, any EUR that you hold is cash, and is equivalent to any other EUR you hold (fungible). This is not equivalent to the value of your apartment, since that fluctuates with respect to EUR. Read on:


>     * Balancing based on commodities seems intuitive at first but I started to stumble as soon as I wanted to include my real estate (which I tracked in EUR)

Ah, good point. In this case, may I point out that you don't really have EUR. Instead, you have an apartment. In other words, you're holding a commodity at cost. A standard way to book this would be like any other stock held at cost:

````
2010-01-01 "Apartment purchase"
   Assets:RealEstate 1 HOMEAPT {100000 EUR}
   Assets:Banks:Bank1 -100000 EUR

2010-01-01 commodity HOMEAPT
   asset_allocation_realestate: 100
````

Then, you could include a price directive any time you want to revise the current value of the apartment, or simply never do that and use the cost price instead.


>     * Assigning individual account to a asset classes would ease changes as I do not have/need a commodity for every asset

This would break the general case, and thus most people's accounts: for example, my beancount brokerage account reflects my real world brokerage account, which has several commodities with different asset classes. How would your approach work for this case?


> Real world examples form my beancount file:
> 
>     * As I mentioned above I track my real estate in EUR since that is what their value is measured at. I did pay x for that house/appartment and do not track if its value changes over the years. The only moment I care about the "real" value is when it is sold.

Which is *exactly* how stocks operate

>     * I lend out money via Mintos. Those loans are in EUR, however I would like to see those on their own, as they are a somewhat risky asset class and not the same as money in my nest egg.

This is an interesting example. I'd argue here for using a price conversion (eg, MINTOS), and assigning it a different asset class, because 1 EUR loaned out via Mintos is *not* equivalent to 1 EUR held in your bank, given their different risk profiles. They can't simply be added up to understand your net worth, for example. I'd book it this way:

````
2011-01-01 "Loaned out"
  Assets:Investments:LoadnedOut 1000 MINTOS @ 1 EUR
  Assets:Banks:Bank1 -1000 EUR
````

Thoughts?

**Comment by Mirodin** [comment]
> ```
> --accounts "Assets:Investments:Brokerage.*" "Assets:Banks:Bank1" "Assets:Banks:Bank3"
> ```
> 
> Does that help?

It does indeed, I did not know that.

> Ah, good point. In this case, may I point out that you don't really have EUR. Instead, you have an apartment. In other words, you're holding a commodity at cost. A standard way to book this would be like any other stock held at cost:
> 
> ```
> 2010-01-01 "Apartment purchase"
>    Assets:RealEstate 1 HOMEAPT {100000 EUR}
>    Assets:Banks:Bank1 -100000 EUR
> 
> 2010-01-01 commodity HOMEAPT
>    asset_allocation_realestate: 100
> ```
> 
> Then, you could include a price directive any time you want to revise the current value of the apartment, or simply never do that and use the cost price instead.

Unfortunately this example does not work for me, beancount spits at me:

`Error: unable to convert 1 HOMEAPT to base currency EUR (Missing price directive?)`

I got the same error for my P2P "currency" but could fix it by creating a single price directive (though a little weird). Any ideas?

> This is an interesting example. I'd argue here for using a price conversion (eg, MINTOS), and assigning it a different asset class, because 1 EUR loaned out via Mintos is _not_ equivalent to 1 EUR held in your bank, given their different risk profiles. They can't simply be added up to understand your net worth, for example. I'd book it this way:
> 
> ```
> 2011-01-01 "Loaned out"
>   Assets:Investments:LoadnedOut 1000 MINTOS @ 1 EUR
>   Assets:Banks:Bank1 -1000 EUR
> ```

Even though I read the beancount documentation I did not quite get what commodities are and did treat them like currencies. Using them this way is way more flexible than my proposal, thanks again for explaining this to me!

**Comment by redstreet** [comment]
> > Then, you could include a price directive any time you want to revise the current value of the apartment, or simply never do that and use the cost price instead.
> 
> Unfortunately this example does not work for me, beancount spits at me:
> 
> `Error: unable to convert 1 HOMEAPT to base currency EUR (Missing price directive?)`
> 
> I got the same error for my P2P "currency" but could fix it by creating a single price directive (though a little weird). Any ideas?

Add this line at the top of your beancount file.
````
plugin "beancount.plugins.implicit_prices" 
````

> Even though I read the beancount documentation I did not quite get what commodities are and did treat them like currencies. Using them this way is way more flexible than my proposal, thanks again for explaining this to me!

Glad it helped!

**Comment by Mirodin** [comment]
> Add this line at the top of your beancount file.
> 
> ```
> plugin "beancount.plugins.implicit_prices" 
> ```

Works like a charm now. Still figuring out what hierarchy fits my needs :)
